### ISSUE TITLE
AttributeError: 'Configuration' object has no attribute 'SCENE'

### ISSUE THREAD

**Issue by Raminmoslemi** [devendrachaplot/Object-Goal-Navigation#2]
Hi
I am trying to reproduce your results, however when I run main.py file, I get following error 
Traceback (most recent call last):
  File "/home/ma/rmoslemi/anaconda3/envs/habitat/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/ma/rmoslemi/anaconda3/envs/habitat/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/net/acadia13a/data/ramin/my_proj/object_navigation/envs/habitat/utils/vector_env.py", line 192, in _worker_env
    observations = env.reset()
  File "/net/acadia13a/data/ramin/my_proj/object_navigation/agents/sem_exp.py", line 62, in reset
    obs, info = super().reset()
  File "/net/acadia13a/data/ramin/my_proj/object_navigation/envs/habitat/objectgoal_env.py", line 321, in reset
    self.scene_name = self.habitat_env.sim.config.SCENE
AttributeError: 'Configuration' object has no attribute 'SCENE'
I0429 16:04:39.295415 23132 Simulator.cpp:49] Deconstructing Simulator
I0429 16:04:39.436203 23133 Renderer.cpp:34] Deconstructing Renderer

the error originally belongs 
obs, infos = envs.reset() 

I took a look on envs/habitat/objectgola_env.py and I could not find where you define self.habitat_env.sim.config.SCENE for  ObjectGoal_Env class. 
 

Just to add i am using the stable version of habitat sim and lab.  However, I do not think the error related to habitat versions .

**Comment by srama2512** [comment]
This is likely due to a version mismatch. According to the instructions, specific versions of habitat-sim and habitat-lab should be used. Not the stable versions. 

```
cd habitat-sim; git checkout tags/v0.1.5; 
```

```
cd habitat-lab; git checkout tags/v0.1.5; 
```

A relevant issue:
https://github.com/facebookresearch/habitat-lab/issues/429

**Comment by devendrachaplot** [comment]
Closing due to inactivity, please update if the solution worked for you.
